Add AlpsItem resource
ma-alps/MaAlps.MaAlps pull request #7
Opened 2021-07-02 11:06 UTC by poemn

- add AlpsCommand, AlpsQuery interface
- add AlpsItem resource

2021-07-02 12:10 UTC, koriym approved these changes

2021-07-02 12:51 UTC, NaokiTsuchiya approved these changes

2021-07-03 00:11 UTC, koriym commented on bin/setup.php
> -declare(strict_types=1);
機械的に付加しておいて良いですね。

例えばインターフェイスでは`declare(strict_types=1);`の意味は無いのですがCSチェックでエラーになってしまうますが、その対策（防いだり、あるいはインターフェイスなら除去する）の手段がないので機械的に付加されてます。

2021-07-03 00:12 UTC, koriym commented on bin/setup.php
> -declare(strict_types=1);
@poemn ここの除去は意図的なものでなく、 単にコピペの時にって感じですよね 😅

2021-07-03 00:17 UTC, koriym commented
コンテキスト説明

@acio-o9 なぜSQLのスタイルがこんな風になっているかというとこのSQLスタイルを採用してフォーマットしているからです。

![image](https://user-images.githubusercontent.com/529021/124337754-29c68c80-dbdf-11eb-8042-93b55842e486.png)

Joe Celkoさんという"SQLレジェンド"がいて、その人のフォーマットがPhpStormにプリセットされていてそれを使おうということになりました。

PhpStorm > Preferrence > Code Style > SQL > General > Set from... > Joe Celko ≒ https://sqlstyle.guide

https://www.sqlstyle.guide/ja/

ここで説明されているフォーマットとほぼ同じです。

2021-07-03 00:24 UTC, koriym requested changes

2021-07-03 00:24 UTC, koriym commented on src/Resource/App/AlpsItem.php
> +     * @return $this
不要です。

2021-07-03 00:24 UTC, koriym commented on var/sql/alps_item.sql
> +SELECT id, is_public, title, user_id, asd_url, profile_url, media_type
コメント入れましょうか？ 皆さんどう思われますか。

2021-07-03 00:24 UTC, koriym commented on var/sql/alps_list.sql
> + WHERE id = :id;
listとitemが逆になってます。

2021-07-09 00:06 UTC, NaokiTsuchiya requested changes

2021-07-09 00:06 UTC, NaokiTsuchiya commented on var/phinx/migrations/20210702060107_alps.php
> +declare(strict_types=1);
生成されたファイルですが、 他のフォーマットに合わせて `<?php` のあとに空行があっても良いかもしれません。

2021-07-09 00:06 UTC, NaokiTsuchiya commented on var/phinx/phinx.php
> +use BEAR\Dotenv\Dotenv;
-  `<?php` のあとに空行があっても良いかもしれません。
- strict 指定

2021-07-09 06:21 UTC, NaokiTsuchiya commented on src/Resource/App/AlpsItem.php
> +     * @param string $id Alps Id
API doc がいい感じにやってくれるので不要だった

2021-07-09 07:03 UTC, NaokiTsuchiya approved these changes

2021-07-09 07:04 UTC, acio-o9 approved these changes

2021-07-09 07:06 UTC, shotanue commented
LGTM

2021-07-09 07:07 UTC, shotanue approved these changes
LGTM

2021-07-09 07:07 UTC, koriym approved these changes

2021-07-09 07:07 UTC, merged